### PR TITLE
 floating ips with openstack

### PR DESCRIPTION
**Pull request by jyriok**
add ops file for manage floating ips with openstack

(initialy for use it with bucc : https://github.com/starkandwayne/bucc/pull/103 )

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Hi - thanks for the PR. If you can take care of the CLA first, that would be helpful.

Change seems okay to me; @voelzmo?

**Comment by voelzmo** [comment]
Hey @jyriok,

Thanks for the PR. Could you please help me understand what your use-case for this ops-file is?
Are you using `bosh create-env` and want a director with a floating ip, such that you can reach it from outside of OpenStack? In this case, I'd recommend using the already existing ops-file https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-with-registry-not-recommended.yml

PS: Did you try using the ops-file? I'd be curious if it works, because you didn't adapt the IP address for the Director's certificate. Any connection to the Director using the floating ip should fail, because the  Certificate is signed for the private IP still.

**Comment by jyriok** [comment]
hi 
it's because i use BUCC who deploy  bosh-director/UAA/Concourse & Credhub on the same instance.
and as i have Concourse on it, i need a external ip address for access to the interface. it's only for that

the ops file you show me does'nt fit for my requirement as it modify ip for bosh and , as you say, thats not recommanded.

But maybe my opsfile is more for bucc than bosh-deployment. 

for the CLA : the only method actually is to fill a paper with my identity ? i've see on some projects a button for just accept CLA

**Comment by voelzmo** [comment]
Well, here is what your ops-file does: It adds a floating ip to the machine where the Director is installed to, this includes CredHub and the UAA – and in your case with BUCC also Concourse. However, as all of those services are running on the same VM, they all get exposed to the outside. Essentially, you are doing exactly what the ops-file I referenced does, with two exceptions:
* the ops-file I referenced also changes the Director certificate, such that you'd talk to your Director using the floating ip. I can understand that this is not what you want to do, and therefore you still want the private ip in the certificate for TLS validation
* The ops-file also enables you to install your Director from the outside of OpenStack, therefore the changes to the `ssh_tunnel` properties

It seems that your need isn't really related to bosh-deployment, but rather to the fact that BUCC installs concourse on the same VM and you want to assign a floating ip to concourse. In that case, you'd probably want to also include that floating ip in the certificate for concourse's ATC in the same way that the ops-file I referenced above does it for the Director. Therefore, I'd recommend that the change you're requesting should live in BUCC, not in bosh-deployment.

**Comment by jyriok** [comment]
i agree with you and i close this issue.
thanks for your analyse and your time. :)

**Pull request closed without merging**
