### PR TITLE
configurable certificate duration for bosh

### PR DESCRIPTION
**Pull request by adam-jian-zhang**
Sometimes it's useful to give the certificate longer time to reduce
the need to rotation. Exposed certificate_duration variable for user
to customize bosh/credhub/uaa certificate duration.

Note: Please create PR's against the develop branch

### CODE REVIEW

**Review by rkoster — CHANGES_REQUESTED** [review]
Please convert to ops-file syntax as discussed offline 😄

**Comment by adam-jian-zhang** [comment]
@rkoster, I have done the conversion, please have a review.

**Review by rkoster — CHANGES_REQUESTED** [review]
No need for: tests/run-ten-year-bosh.sh unit test is enough for these ops-files.

Could you also rename `misc/configurable-duration-bosh` to `misc/certificate-duration`

**Comment by adam-jian-zhang** [comment]
> 

Done

**Review by ramonskie — APPROVED** [review]
LGTM

**Review by rkoster — APPROVED** [review]
LGTM

**Comment by rkoster** [comment]
Thanks! @adam-jian-zhang

**Pull request merged**
