### PR TITLE
No internet access

### PR DESCRIPTION
**Pull request by clijockey**
A number of the default manifest configurations assume that the host you are deploying from has access to the Internet. In a number of cases I have worked in environment that do not and run on a restricted on-prem vSphere environment.

As a result I have create some ops files to alter the manifests to use local instances of the CPI, stemcell and bosh-release. I have also added an opt for UAA and Credhub.

I know that a some `local-bosh-release` opts exist however that is just a small part of the story to deploy a bosh director when not connected directly to the Internet.

I place in experimental because I wasn't sure what the preferred location would be.

### CODE REVIEW

**Comment by clijockey** [comment]
Hello, to be covered under the Pivotal CLA which of the numerous Orgs should I be a member of?

**Comment by christopherclark** [comment]
Hi Rob,

The following pivotal orgs are all covered by a CLA:
pivotal, pivotal-cf, pivotal-field-engineering, pivotal-golang

**Comment by clijockey** [comment]
@christopherclark thanks for that, I have now been added to the pivotal-cf org and made it public on my profile.

**Comment by cppforlife** [comment]
@clijockey let's place them under `misc`. eg misc/no-internet/uaa.yml

also should be local_cpi -> local_vsphere_cpi

**Comment by clijockey** [comment]
Hey @cppforlife, I have incorporate the suggested changes.

**Comment by clijockey** [comment]
Although I have just noticed that I went away with my gut instinct to call the bosh specific one `vsphere-cpi-and-stemcell.yml` rather than `bosh.yml` like the IPv6 folder does. Would you prefer me to alter it back or keep as is?

**Comment by cppforlife** [comment]
i've split stemcell from vsphere-cpi in https://github.com/cloudfoundry/bosh-deployment/commit/6258117414e5f33cd1b1fc7a804a2a4e67c3eedd. we allow multiple cpis to be present on the director for multi-cpi configuration so want to keep them separate.

**Pull request merged**
