### PR TITLE
Updated Bionic stemcell version

### PR DESCRIPTION
**Pull request by StefanWutz**
Use the lastest Bionic beta version 0.16.

### CODE REVIEW

**Comment by mrosecrance** [comment]
Does it make sense to hold off until the gcp stemcell is fixed?

**Comment by StefanWutz** [comment]
Sure, we can hold off. Do you have more information about the gcp issue?

**Comment by StefanWutz** [comment]
- Updated to version 0.18.
- Updated softlayer and alicloud light stemcell to latest available version 0.16.

**Comment by StefanWutz** [comment]
@mrosecrance I have updated all ops files for bionic to the latest version.

**Pull request merged**
