### PR TITLE
generate credhub_dev_key as password

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by rkoster** [comment]
this does not work since `dev_key` needs to be [`32` chars](https://github.com/pivotal-cf/credhub-release/blob/0.5.1/jobs/credhub/templates/application.yml.erb#L68-L72) and generated passwords are only [20 chars](https://github.com/cloudfoundry/config-server/blob/master/types/password_generator.go#L13)

**Comment by drnic** [comment]
Closing in lieu of #37 which I hadn't seen.

**Comment by pivotal-danjahner** [comment]
@drnic We've changed the encryption key specification in the upcoming version of CredHub (0.6.0) to accept a variable-length password, instead of a 32 char hex string. I'll PR the credhub.yml when that version lands.

**Comment by rkoster** [comment]
nice will, be nice to use `variables` for the `dev_key`

**Pull request closed without merging**
