### PR TITLE
Update runtime config on virtual box create script

### PR DESCRIPTION
**Pull request by cdutra**

### CODE REVIEW

**Comment by jfmyers9** [comment]
Hi @cdutra,

Due to the nature of runtime configs being non-essential to a functioning BOSH environment, we're hesitant to include this `update-runtime-config` in the virtual box script.

What is your current use case for adding this? Is there some way that we could output the necessary command to do so on `stdout` to make this process somewhat easier for users?

Let us know what you think,

@jfmyers9 && @belinda-liu, CF BOSH

**Comment by cdutra** [comment]
Hi @jfmyers9, It's more for trying to make sure bosh-dns is configured out of the box and avoid forgetting to set and having your cf deployment fail.

**Comment by voelzmo** [comment]
Given the fact that bosh-deployment now configures local-dns to be enabled, I'm not sure what the use-case is to *not* upload a runtime config co-locating bosh-dns-release afterwards. So I'd say we either default local-dns to `false` and make the whole thing optional, or we also automatically upload the runtime-config to be able to make use of bosh-dns

**Comment by belinda-liu** [comment]
Hey @cdutra, after some further discussion in the team and to @voelzmo's point, it does make more sense to have this runtime config uploaded right away. Merging this now, thanks for the submission.

**Pull request merged**
