### PR TITLE
Corrected invalid link to "Differences between CLI v2 vs v1"

### PR DESCRIPTION
**Pull request by wildloop**

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Thanks - this is a great fix. I think technically we're required to have a signed CLA in order to merge which is probably why this is still sitting here. If you're able to sign it, that'd be very helpful!

**Comment by wildloop** [comment]
Hi @dpb587-pivotal,
Should I print&sign the individual CLA, scan it and send an email (what address)?

**Comment by dpb587-pivotal** [comment]
Hi - if you could sign the PDF and then send it to the address listed in the PDF. If you're signing the [individual CLA](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf) you can email it to contributors@cloudfoundry.org. Hopefully getting this done once will make future PRs easier :)

Thanks!

**Comment by wildloop** [comment]
thanks, I already sent it.
I attached CLA with PDF forms, it will be more comfortable to fill:
[CFF_Individual_CLA-pdf-forms.pdf](https://github.com/cloudfoundry/bosh-deployment/files/1253353/CFF_Individual_CLA-pdf-forms.pdf)

**Comment by wildloop** [comment]
I have already signed the CLA, please merge this fix.

**Pull request closed without merging**
