### PR TITLE
Add external IP config for CredHub

### PR DESCRIPTION
**Pull request by pivotal-danjahner**
Enables external access, by request of BBL team.

### CODE REVIEW

**Comment by evanfarrar** [comment]
:+1:

We may have to fork this repo in order to get this and #37 to add support for credhub to bbl. After that, all bbl users will use the fork rather than getting master@HEAD periodically from our CI.

**Comment by cppforlife** [comment]
@evanfarrar 

> We may have to fork this repo
far from ideal. let's get the jumpbox config figured out. goal for bbl is to configure secure by default bosh envs so i dont think we should exposing credhub to the world by default.

**Comment by cppforlife** [comment]
@pivotal-danjahner closing this. let's chat more about cli support for socks5 proxy.

**Comment by aclevername** [comment]
@cppforlife any update on whether this can be accepted now?

**Pull request closed without merging**
