### PR TITLE
Add stemcell OS and version to compiled releases

### PR DESCRIPTION
**Pull request by voelzmo**
Supporting the use-case of just updating the stemcell without updating
the release. Otherwise, uploading the compiled release will not happen,
because the director just checks for name and version in its DB.

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
You and your `bosh deploy` habits :)

I like the change since it better matches our recommendations of using `stemcell`, but I think, for at least `bosh.yml`, those URLs (and, implicitly, stemcell) are automatically updated by [`ci/tasks/use-latest-release.sh`](https://github.com/cloudfoundry/bosh-deployment/blob/master/ci/tasks/use-latest-release.sh). Interested in changing that script, too?

**Comment by voelzmo** [comment]
> You and your `bosh deploy` habits :)

Are you suggesting I'm the only one deploying bosh with bosh? I'd say it is the most reasonable thing to do, given the lack of monitoring and resurrection otherwise. ;P

I'll push a change to modify the CI script as well, thanks for the pointer.

**Comment by voelzmo** [comment]
caveat: I didn't actually set the pipeline and test this. You might want to double check that I didn't do any weird yml mistakes here.

**Comment by jfmyers9** [comment]
This has gotten stale and we would need to work this into our new automation around bumping versions of releases. I'm going to close this, and we can consider improving our automation.

**Pull request closed without merging**
