### PR TITLE
Allow DNS to be configured by `internal_dns` Operations File

### PR DESCRIPTION
**Pull request by Oskoss**

### CODE REVIEW

**Comment by tylerschultz** [comment]
This could instead be done with an ops file. It may look something like this:
```
---
- type: replace
  path: /networks/name=default/subnets/0/dns
  value: [((internal_dns)),8.8.8.8]
```

**Comment by Oskoss** [comment]
@tylerschultz Makes sense. Will change this up tonight. Any reason why we require everything on the network besides DNS? If only for convention shouldn't we ask for internal_dns as well?

**Comment by tylerschultz** [comment]
That's a fair point. I am not aware of any specific reason why.

**Comment by cppforlife** [comment]
> If only for convention shouldn't we ask for internal_dns as well?

most people still end up using external dns provider afaik so we've decided to keep it as an easy default. if someone needs to override, ops file should be pretty easy.

**Comment by Oskoss** [comment]
@tylerschultz @cppforlife Simplified this through the use of Operations File! :)

**Comment by tylerschultz** [comment]
@Oskoss Have you signed the CLA?

**Comment by Oskoss** [comment]
@tylerschultz Yes!!

**Comment by dpb587-pivotal** [comment]
This has come up a couple times, so I went ahead and merged it. I did [tweak](https://github.com/cloudfoundry/bosh-deployment/commit/75f198e77b3ec61dc8c131c481ec79b5560d516b) it such that it overwrites the DNS servers rather than prepends one (to support multiple servers, and avoid surprises about outbound requests being sent). Only caveat is users should be sure to wrap a single DNS server with square brackets, so the CLI interprets it as an array (so I added a short example in the file comment, as well).

**Comment by dpb587-pivotal** [comment]
And thanks!

**Comment by zmb3** [comment]
Note that the existing operations files and variables use a hyphen instead of an underscore.  Since this was just merged, it might make sense to be consistent with everything else and use *internal-dns.yml* and a variable of `{{internal-dns}}` before it starts getting usage.

**Comment by dpb587-pivotal** [comment]
Oops, you're right, the file should be named internal-dns.yml - missed that
and will fix that shortly.

The variable names though should indeed be underscores. Are there vars in
this repo using dashes? We should fix those, too.

-- 
Danny Berger

**Comment by zmb3** [comment]
> The variable names though should indeed be underscores. Are there vars in
this repo using dashes? We should fix those, too.

You're right.  I guess I just imagined it.  I don't see any variables using dashes.

**Comment by cppforlife** [comment]
@dpb587-pivotal @zmb3 i moved a few things into `misc/` including dns configuration.

**Pull request merged**
