### PR TITLE
alternate cloud-config for multi-az

### PR DESCRIPTION
**Pull request by drnic**
@cppforlife this PR (once merged) will feature in a blog post on multi-az bosh/aws

### CODE REVIEW

**Comment by drnic** [comment]
Updated cloud-config to use `reserved: [((internal_gw1))/30]` pattern as suggested by @dpb587-pivotal in #62

**Comment by cppforlife** [comment]
@drnic mind throwing in a test into test.sh

**Comment by cppforlife** [comment]
ping.

**Comment by drnic** [comment]
@cppforlife done, thx

**Comment by cppforlife** [comment]
@drnic now that i think about, should this be an ops file on top of existing `cloud-config.yml`?

**Comment by jfmyers9** [comment]
Closing this due to inactivity.

If you would like to discuss this contribution further, please open a new issue.

**Pull request closed without merging**
