### PR TITLE
Updated create env for GCP

### PR DESCRIPTION
**Pull request by svennela**

### CODE REVIEW

**Comment by svennela** [comment]
I have made my git profile public.

**Comment by cppforlife** [comment]
@svennela is this much diff from: http://bosh.io/docs/init-google. should i just link to it?

**Comment by svennela** [comment]
yes, this is for bosh-lite.

  bosh create-env ~/workspace/bosh-deployment/bosh.yml \
 -o ~/workspace/bosh-deployment/gcp/cpi.yml \
 -o ~/workspace/bosh-deployment/bosh-lite.yml \
 -o ~/workspace/bosh-deployment/jumpbox-user.yml \
 -o ~/workspace/bosh-deployment/gcp/bosh-lite-vm-type.yml \
 -o ~/workspace/bosh-deployment/external-ip-not-recommended.yml \
 --state=./gcp-bosh-director.json \
 --vars-store=./gcp-bosh-director-creds.yml \
 -v director_name=gcp-bosh-cf \
 -v internal_cidr=10.0.0.0/24 \
 -v internal_gw=10.0.0.1     \
 -v internal_ip=10.0.0.10 \
 --var-file gcp_credentials_json="<gcp_credentials_json>.json" \
 -v project_id=<your_gcp_project>\
 -v zone=<zone>\
 -v tags=[tag1] \
 -v external_ip=<external_ip> \
 -v network=<network> \
 -v subnetwork=<network>

**Comment by dpb587-pivotal** [comment]
Instead of the large duplication, it might make more sense to have a bosh-lite-specific readme or header section which describes what bosh-lite is and then essentially says "add `-o bosh-lite.yml` for this feature". Or perhaps make the `bosh-lite-on-vbox` readme a bit more generic so it's not just vbox.

**Comment by svennela** [comment]
Make sense to create bosh-lite-on-vbox. I will create new PR for that.

**Comment by dpb587-pivotal** [comment]
Feel free to open a new, docs-focused PR.

**Pull request closed without merging**
