### PR TITLE
OpenStack multi-tenant support

### PR DESCRIPTION
**Pull request by jhvhs**
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

### CODE REVIEW

**Comment by cppforlife** [comment]
@jhvhs is this similar to keystone v3? or is tenant also allowed with domain/project?

**Comment by voelzmo** [comment]
Nope, tenant is a keystone-v2 thing. So @jhvhs https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/keystone-v2.yml should already give you what you're looking for. Let me know if you need something different.

**Comment by cppforlife** [comment]
@voelzmo does that ops file (https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/keystone-v2.yml) look right? shouldnt it be doing same thing for both job and cloud provider sections?

**Comment by voelzmo** [comment]
@cppforlife good catch, I issued a PR to fix it.

**Comment by jhvhs** [comment]
@voelzmo In addition to that, we would suggest to add an `openstack_` prefix to the variables used in the `keystone-v2.yml` file.

**Comment by voelzmo** [comment]
https://github.com/cloudfoundry/bosh-deployment/pull/23

**Comment by jhvhs** [comment]
thanks @voelzmo

**Pull request closed without merging**
